### ISSUE TITLE
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1

### ISSUE THREAD

**Issue by regonza** [thekosmix/Java-WhatsappChatBot#1]
Hi, I get the following error after enter start:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at in.strollup.whatsapp.main.WebWhatsapp.reply(WebWhatsapp.java:123)
	at in.strollup.whatsapp.main.WebWhatsapp.responseNonSelectedWindow(WebWhatsapp.java:116)
	at in.strollup.whatsapp.main.WebWhatsapp.openWhatsapp(WebWhatsapp.java:94)
	at in.strollup.whatsapp.main.WebWhatsapp.main(WebWhatsapp.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
Any suggestions?

**Comment by thekosmix** [comment]
This project is not complete and it's not yet being maintained. 
The reason for this error is that the div name might have been changed in web.whatsapp.com. If you'll debug it, you'll be able to fix it.
